# Generated by Django 3.2.7 on 2022-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20220811_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='Home/%Y/%m/'),
        ),
    ]
