# Generated by Django 3.2.7 on 2022-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20220811_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
